spring.application.name=asistencia
spring.datasource.url=jdbc:oracle:thin:@libro_high?TNS_ADMIN=C:/Users/lyla_/Desktop/LibroVirtual/Wallet_libro
spring.datasource.username=ADMIN
spring.datasource.password=81833345Lya_
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
server.port=8083
